package cc.thonly.mystias_izakaya.datagen;

import cc.thonly.mystias_izakaya.datagen.generator.IngredientProvider;
import cc.thonly.mystias_izakaya.item.MIItems;
import cc.thonly.mystias_izakaya.registry.FoodProperties;
import cc.thonly.reverie_dreams.block.ModBlocks;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.item.Items;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class MIIngredientProvider extends IngredientProvider {
    public MIIngredientProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> future) {
        super(output, future);
    }

    @Override
    public void configured() {
        this.createFactory(FoodProperties.AQUATIC_PRODUCTS)
                .add(MIItems.TROUT)
                .add(MIItems.HAGFISH)
                .add(MIItems.SALMON)
                .add(MIItems.TUNA)
                .add(MIItems.SUPREME_TUNA)
                .add(Items.PUFFERFISH)
                .add(MIItems.SHRIMP)
                .add(MIItems.OCTOPUS)
                .add(MIItems.SEA_URCHIN)
                .add(MIItems.CRAB)
                .build();
        this.createFactory(FoodProperties.BIZARRE)
                .add(MIItems.CICADA_SHELL)
                .build();
        this.createFactory(FoodProperties.CHINESE_STYLE)
                .build();
        this.createFactory(FoodProperties.COOL)
                .add(ModBlocks.MAGIC_ICE_BLOCK.asItem())
                .add(MIItems.FICUS_MICROCARPA)
                .build();
        this.createFactory(FoodProperties.CURSE)
                .add(MIItems.PUFF_YO_FRUIT)
                .add(MIItems.CAPSAICIN)
                .build();
        this.createFactory(FoodProperties.CULTURAL_DEPTH)
                .add(MIItems.MOONFLOWER)
                .add(MIItems.TWIN_LOTUS)
                .add(MIItems.LOTUS_NUTS)
                .build();
        this.createFactory(FoodProperties.DARK_CUISINE)
                .build();
        this.createFactory(FoodProperties.DREAMLIKE)
                .add(MIItems.UDUMBARA)
                .add(MIItems.MOONFLOWER)
                .add(MIItems.TWIN_LOTUS)
                .add(MIItems.FLOWERS)
                .add(MIItems.FICUS_MICROCARPA)
                .build();
        this.createFactory(FoodProperties.ECONOMICAL)
                .build();
        this.createFactory(FoodProperties.EXPENSIVE)
                .build();
        this.createFactory(FoodProperties.FIERY)
                .add(MIItems.CHILI)
                .build();
        this.createFactory(FoodProperties.FILLING)
                .add(Items.PUMPKIN)
                .add(MIItems.FLOUR)
                .add(MIItems.SWEET_POTATO)
                .add(Items.COCOA_BEANS)
                .build();
        this.createFactory(FoodProperties.FLAMING)
                .build();
        this.createFactory(FoodProperties.FRUITY)
                .add(MIItems.PEACH)
                .add(MIItems.GRAPE)
                .add(MIItems.LEMON)
                .build();
        this.createFactory(FoodProperties.GOURMET)
                .add(MIItems.SALMON)
                .add(MIItems.TUNA)
                .add(MIItems.WAGYU_BEEF)
                .add(MIItems.TRUFFLE)
                .add(MIItems.SUPREME_TUNA)
                .add(MIItems.UDUMBARA)
                .add(MIItems.SEA_URCHIN)
                .add(MIItems.CRAB)
                .add(MIItems.TWIN_LOTUS)
                .add(MIItems.CHEESE)
                .add(MIItems.PINE_NUT)
                .build();
        this.createFactory(FoodProperties.GREASY)
                .add(MIItems.BUTTER)
                .build();
        this.createFactory(FoodProperties.GRILLED)
                .build();
        this.createFactory(FoodProperties.GOOD_WITH_ALCOHOL)
                .add(MIItems.WHITE_RADISH)
                .build();
        this.createFactory(FoodProperties.HOMESTYLE)
                .add(MIItems.TOFU)
                .add(Items.POTATO)
                .add(MIItems.CUCUMBER)
                .add(MIItems.CREAM)
                .add(MIItems.CHESTNUT)
                .add(MIItems.RED_BEANS)
                .add(MIItems.BROCCOLI)
                .build();
        this.createFactory(FoodProperties.JAPANESE_STYLE)
                .build();
        this.createFactory(FoodProperties.LARGE_PARTITION)
                .build();
        this.createFactory(FoodProperties.LEGENDARY)
                .add(MIItems.BLACK_PORK)
                .add(MIItems.WAGYU_BEEF)
                .add(MIItems.TRUFFLE)
                .add(MIItems.SUPREME_TUNA)
                .add(MIItems.UDUMBARA)
                .add(MIItems.SEA_URCHIN)
                .add(MIItems.TWIN_LOTUS)
                .build();
        this.createFactory(FoodProperties.LIGHT)
                .add(MIItems.TOFU)
                .add(MIItems.DEW)
                .add(MIItems.BAMBOO_SHOOTS)
                .add(MIItems.MOONFLOWER)
                .add(MIItems.CUCUMBER)
                .add(MIItems.TWIN_LOTUS)
                .add(MIItems.LOTUS_NUTS)
                .add(MIItems.PINE_NUT)
                .add(MIItems.TREMELLA)
                .build();
        this.createFactory(FoodProperties.LOCAL_SPECIALTY)
                .build();
        this.createFactory(FoodProperties.MEAT)
                .add(Items.PORKCHOP)
                .add(Items.BEEF)
                .add(MIItems.VENISON)
                .add(MIItems.WILD_BOAR_MEAT)
                .add(MIItems.BLACK_PORK)
                .add(MIItems.WAGYU_BEEF)
                .build();
        this.createFactory(FoodProperties.MUSHROOMS)
                .add(Items.RED_MUSHROOM)
                .add(Items.BROWN_MUSHROOM)
                .add(MIItems.TRUFFLE)
                .add(MIItems.TREMELLA)
                .build();
        this.createFactory(FoodProperties.MOUNTAIN_DELICACY)
                .add(MIItems.BLACK_PORK)
                .add(MIItems.TRUFFLE)
                .build();
        this.createFactory(FoodProperties.OCEAN_FLAVOR)
                .add(MIItems.SUPREME_TUNA)
                .add(Items.PUFFERFISH)
                .add(MIItems.OCTOPUS)
                .add(MIItems.SEA_URCHIN)
                .build();
        this.createFactory(FoodProperties.PETITE)
                .add(MIItems.PLUM)
                .build();
        this.createFactory(FoodProperties.PHOTOGENIC)
                .add(MIItems.GINKGO)
                .add(Items.BAMBOO)
                .add(MIItems.FLOWERS)
                .build();
        this.createFactory(FoodProperties.POPULAR_NEGATIVE)
                .build();
        this.createFactory(FoodProperties.POPULAR_POSITIVE)
                .build();
        this.createFactory(FoodProperties.POWER_SURGE)
                .build();
        this.createFactory(FoodProperties.RAW)
                .add(Items.EGG)
                .build();
        this.createFactory(FoodProperties.SALTY)
                .add(MIItems.BLACK_SALT)
                .add(MIItems.CHEESE)
                .add(MIItems.PLUM)
                .build();
        this.createFactory(FoodProperties.SIGNATURE)
                .add(MIItems.HAGFISH)
                .add(MIItems.LOTUS_NUTS)
                .add(MIItems.PINE_NUT)
                .build();
        this.createFactory(FoodProperties.SOUR)
                .add(MIItems.LEMON)
                .build();
        this.createFactory(FoodProperties.SPICY)
                .build();
        this.createFactory(FoodProperties.SWEET)
                .add(MIItems.PEACH)
                .add(Items.HONEY_BOTTLE)
                .add(MIItems.GRAPE)
                .add(MIItems.CREAM)
                .build();
        this.createFactory(FoodProperties.SOUP_AND_STEW)
                .build();
        this.createFactory(FoodProperties.TOXIC)
                .add(MIItems.TOON)
                .build();
        this.createFactory(FoodProperties.UMAMI)
                .add(MIItems.ONION)
                .add(MIItems.TROUT)
                .add(MIItems.HAGFISH)
                .add(MIItems.SALMON)
                .add(MIItems.TUNA)
                .add(Items.RED_MUSHROOM)
                .add(Items.BROWN_MUSHROOM)
                .add(MIItems.TRUFFLE)
                .add(MIItems.SUPREME_TUNA)
                .add(Items.PUFFERFISH)
                .add(MIItems.SHRIMP)
                .add(MIItems.OCTOPUS)
                .add(MIItems.SEA_URCHIN)
                .add(MIItems.CRAB)
                .add(MIItems.CHEESE)
                .build();
        this.createFactory(FoodProperties.UNBELIEVABLE)
                .add(MIItems.UDUMBARA)
                .add(MIItems.MOONFLOWER)
                .add(Items.COCOA_BEANS)
                .build();
        this.createFactory(FoodProperties.VEGETARIAN)
                .add(MIItems.TOFU)
                .add(Items.POTATO)
                .add(MIItems.ONION)
                .add(Items.PUMPKIN)
                .add(MIItems.WHITE_RADISH)
                .add(Items.KELP)
                .add(Items.RED_MUSHROOM)
                .add(Items.BROWN_MUSHROOM)
                .add(MIItems.TRUFFLE)
                .add(MIItems.BAMBOO_SHOOTS)
                .add(MIItems.CUCUMBER)
                .add(MIItems.CHESTNUT)
                .add(MIItems.TOON)
                .add(MIItems.TOMATO)
                .add(MIItems.BROCCOLI)
                .build();
        this.createFactory(FoodProperties.WESTERN_STYLE)
                .add(MIItems.CREAM)
                .build();
    }

    @Override
    public String getName() {
        return "Mystia's Izakaya MIIngredient Generator";
    }
}
